stages:
  prepare:
    cmd: python src/prepare.py data/data.csv
    deps:
    - data/data.csv
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurization.py data/prepared/train.csv data/prepared/test.csv
      data/features/train.pkl data/features/test.pkl
    deps:
    - data/prepared/test.csv
    - data/prepared/train.csv
    - src/featurization.py
    params:
    - featurize.n_components
    outs:
    - data/features/test.pkl
    - data/features/train.pkl
  train:
    cmd: python src/train.py data/features model.pkl
    deps:
    - data/features
    - src/train.py
    params:
    - train.min_split
    - train.n_est
    - train.seed
    outs:
    - model.pkl
  evaluate:
    cmd: python src/evaluate.py model.pkl data/features
    deps:
    - data/features
    - model.pkl
    - src/evaluate.py
    outs:
    - eval
